### PR TITLE
fix: scrapped data from actions can commit

### LINKED ISSUE #17: URGENT: Scraped data from actions won't commit

### PR DESCRIPTION
**Pull request by alan1420**
trying to fix #17

### CODE REVIEW

**Comment by angeloanan** [comment]
Does this fix works on your fork?

Selama ini aku suspek filenya ngga keganti / ngga overwrite. If this works on your fork then I've just wasted like 3 hours finguring out wtf is wrong with my code 😢

**Comment by alan1420** [comment]
Yes. Tadi aku coba dengan edit data.json terus run workflownya

**Comment by angeloanan** [comment]
Let's try this out 🤞

**Comment by angeloanan** [comment]
Working as intended in 13de42c102922ea80a1cca74b296e34325312003. Thanks alot!

**Comment by alan1420** [comment]
You're welcome 👌

**Pull request merged**
